services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
        - db-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-ml_database}"]
      interval: 5s
      timeout: 5s
      retries: 5

  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data:/app/data
      - kaggle_cache:/root/.cache/kagglehub

    networks:
        - db-net
    tty: true

networks:
  db-net:
    driver: bridge

volumes:
  postgres_data:
  kaggle_cache:
